### ISSUE TITLE
Visual automation keyboard() and click() not working on MacOS Big Sur - KIV

### ISSUE THREAD

**Issue by ewyllie** [tebelorg/RPA-Python#298] opened 2021-08-30 14:29 UTC
**OS**: MacOS Big Sur 11.4
**Java Version**: JDK-12
**Python Version**: 3.8.8

I have tried testing this library with sample code provided, and cannot get any visual_automation functions to work. The Chrome functions work without issue but click and keyboard functions hang until timeout. I have followed steps from other issues such as checking logs and allowing java and the terminal accessibility permissions. None of these seem to have any effect. The Java app opens and closes whilst attempting to run.

<img width="510" alt="Screenshot 2021-08-30 at 15 22 24" src="https://user-images.githubusercontent.com/52719982/131354674-efdc2141-fc75-445a-9591-576cac6dab99.png">
<img width="567" alt="Screenshot 2021-08-30 at 15 24 26" src="https://user-images.githubusercontent.com/52719982/131354689-50f16ea9-9881-4ed8-984e-17e107f41459.png">

**Comment by kensoh** [comment] 2021-08-30 15:57
Hi Ed, I assume that your Java version is 64-bit. Can you share the logs for visual automation?

It is found in r.tagui_location() folder, under it check inside `.tagui/src/tagui.sikuli` folder.

**Comment by ewyllie** [comment] 2021-08-30 16:04
Hi,

Thanks for the quick response.
Here is the contents of tagui.log

`Exception in thread "main" java.lang.NullPointerException
	at org.sikuli.script.runners.SikulixRunner.doRunScript(SikulixRunner.java:37)
	at org.sikuli.script.runners.AbstractScriptRunner.runScript(AbstractScriptRunner.java:139)
	at org.sikuli.script.support.Runner.run(Runner.java:243)
	at org.sikuli.script.support.Runner.run(Runner.java:236)
	at org.sikuli.script.support.Runner.runScripts(Runner.java:216)
	at org.sikuli.script.support.RunTime.afterStart(RunTime.java:179)
	at org.sikuli.ide.SikulixIDE.main(SikulixIDE.java:109)
IDE terminated: returned: 1
`
Is there some additional configuration for SikulixRunner required?

**Comment by kensoh** [comment] 2021-08-30 16:24
Thanks Ed, not that I know of, this is the first time I see this error reported.

Can you try the steps 1 to 3 below to see if you can run the latest SikuliX version ok?

http://sikulix.com/quickstart/

I'm trying to test whether this is a conflict with the version used or for some reason is also happening for latest SikuliX.

**Comment by ewyllie** [comment] 2021-08-31 20:01
Thanks Ken,

I followed the steps and can open the SikuliX IDE okay - the issue still persists though.

**Comment by kensoh** [comment] 2021-09-01 03:41
I see.. Can you try replacing the file .tagui/src/sikulix/sikulix.jar with the one you downloaded? (rename to sikulix.jar)

**Comment by ewyllie** [comment] 2021-09-01 11:44
Hi Ken,

That seems to work a bit better although still hangs. tagui.log is showing much more activity - it's all debug logs except an error line with the following:
`[error] Mouse: not useable (blocked)`
I haven't yet had the chance to look into this in depth but it seems like there may be some sikulix solutions online.

**Comment by ewyllie** [comment] 2021-09-01 14:13
Hi Ken,

Success! I think it's now. When I was fiddling around with the sikulix IDE I was prompted to allow Visual Studio some accessibility permissions. After doing that it appears to work. Maybe that's all that was needed? (New version of sikulix.jar and accessibility enabled for VS Code).

I can't seem to get the click functions to click on an application on the mac hotbar - is this typical behaviour? It works on other desktop UI elements.

Thank you so much for your help

**Comment by kensoh** [comment] 2021-09-01 16:11
Thanks Ed! Glad that you resolve the problem :) Yes for macOS the security is very strict, so it will need user to allow permission before controlling the computer. I'll keep a lookout for more users having similar issue to see if there is some common root cause, and to find a permanent solution for the problem. Thank you!

**Comment by kensoh** [comment] 2021-09-01 16:12
I'll close the issue now so that user with similar problem can raise it and I can know about it.

**Closed by kensoh** 2021-09-01 16:12 UTC
Labels: query
