### ISSUE TITLE
Multiple instances - no support, use queues, decentralised runs or hacks

### ISSUE THREAD

**Issue by soorejmg** [tebelorg/RPA-Python#124] opened 2020-04-12 03:51 UTC
Hi, 
I am trying to develop a system where multiple users can make use of a tagui process automation. Idea was like this, invoke some web service call and then tagui process runs.  Is it possible to open two chrome windows at a time, one for each user and work for each window. How can this be done? Any inputs pls..

Thanks
Soorej

**Comment by kensoh** [comment] 2020-04-12 04:17
Hi Soorej, that is technically not possible with upstream TagUI architecture. It was designed to prioritise on reliability and stability of execution (for there are production jobs running automation that take more than 10 hours, without issues).

Because of this design choice, there are in-built logic in the design that will restart processes before each run, and that also include Chrome process. Having multiple threads would disrupt the automation actions from another thread.

If you are building a web-service to manage that, this is definitely doable, on the condition that execution are piped into a queue and run consecutively, but not concurrently. If running consecutively is ok for your use case, you can take a look at how I implement TagUI's web-service here - https://github.com/kelaberetiv/TagUI/tree/pre_v6#api

Other ideas that can be explored would be asking users to install Python and then RPA for Python directly on their computers. If concern is automation execution disrupting their work, you can consider hacking the tool to increase execution speed. For eg this RPA Challenge, whre the hack cut down run time from 2 minutes to under 5 seconds - https://github.com/tebelorg/RPA-Python/issues/120#issuecomment-610532082

If concern is still work being disrupted, you can also look at hacking the tool to run in headless mode so that the Chrome web browser does not even appear, and see if that works for your users use scenarios - https://github.com/tebelorg/RPA-Python/issues/109

**Comment by kensoh** [comment] 2020-04-15 02:13
Closing issue for now until further inputs!

**Closed by kensoh** 2020-04-15 02:13 UTC
Labels: query
