### ISSUE TITLE
I can't run the examples on Alma Linux 9 OS - try these steps and see the logs for clues

### ISSUE THREAD

**Issue by debugger1979** [tebelorg/RPA-Python#503] opened 2023-11-13 07:47 UTC
I can't run the examples on Alma Linux 9 OS. When running examples with visualization, the script does not work. The phantomjs process loads one core at 100% and the script freezes.
I check the same script on ArchLinux and it is successful.
I tried updating versions of tesseract, opencv, php in Alma Linux 9, but the result is the same. The phantomjs process loads one CPU core and the script script freezes.
Have you checked the operation of your module on RPM-based operating systems? Maybe there is a solution to the problem?

**Comment by kensoh** [comment] 2023-12-24 13:50
Hi @debugger1979, I have not tested or designed the package and its underlying TagUI engine to work for Alma Linux.

Does it hangs if you do not use visual automation? The issue might be with just the SikuliX interactions with the computer vision libraries on Alma Linux, or a conflict between the PhantomJS engine and those libraries on Alma Linux.

Some possible next steps could be -
1. try installing the libraries using this guide - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html
2. print(r.tagui_location()) and see the tagui or .tagui folder under it. There is a src/tagui.sikuli folder with the SikulIX logs that are related to the computer vision and visual automation libraries

If the issue is outside of PhantomJS which I suspect, it might be resolved by finding out more using step 2 above. If it is a conflict with PhantomJS with the computer vision libraries then it is likely hard to solve because PhantomJS project is a stable mature project and it is no longer being maintained --> archived status.

**Comment by debugger1979** [comment] 2024-01-11 08:06
Hello!
I have solved this problem. The problem was on the surface - in the logs ~/.tagui/src/taguig.sikuli/taguig.log
java couldn't find the opencv_java library (in my case, opencv_java 460.jar ).

Solution (rpm-based Linux):
dnf install opencv opencv-devel opencv-java
It was necessary to install the opencv-java package

Thank you so much for your application! We use it for load testing of applications inside VDI sessions.

**Comment by kensoh** [comment] 2024-01-14 00:18
Hi @debugger1979 thanks for sharing back your findings and solution!!

I'm glad you solve it, and I'm pleasantly surprised on your use case. The package wasn't designed for test automation or load testing, more for making it easy to automate digital workflows. Am happy to hear that it is useful on professional level for load testing!!

**Closed** 2024-01-14 00:18 UTC
Labels: query
