### ISSUE TITLE
Quiet mode for the RPA module? - pending other users' inputs and requests

### ISSUE THREAD

**Issue by jesuisme** [tebelorg/RPA-Python#373] opened 2022-04-13 01:41 UTC
In the TagUI documentation, there is a flag, -q, for running without output to a command prompt. Link to the docs:
https://tagui.readthedocs.io/en/latest/reference.html#run-options

I'd like to ask that quiet mode be added to the next release. In my local RPA-Python repository, I was able to enable this functionality by modifying the tagui.py file. I added a quiet_mode keyword argument to the init() function definition:

    def init(visual_automation = False, chrome_browser = True, headless_mode = False, turbo_mode = False, quiet_mode=False)

and then modified the code at line 531 as follows:

    try:
        # Do not launch a subprocess shell if quiet_mode is turned on
        if quiet_mode:
            shell_option = False
        else:
            shell_option = True

        # launch tagui using subprocess
        _process = subprocess.Popen(
                tagui_cmd, shell=shell_option,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
        )

Thank you for the awesome RPA module!

**Comment by kensoh** [comment] 2022-04-13 09:34
Hi @jesuisme thanks for raising this issue and sharing your modification! I'm happy that you enjoy using rpa package :)

Can you tell me more what is the observable difference to users, between running shell=True or shell=False?

By design, the process runs in the background, so it is not visible to user, the background command prompt process.

**Comment by jesuisme** [comment] 2022-04-13 11:16
@kensoh 

In Windows 11, shell=True causes a Command Prompt to open with the title "Chrome Engine".  The window is a console for the TagUI process, outputing responses to each of the RPA interface functions. For example, the output shown for r.init():

    [tagui] START  - listening for inputs
    
    [tagui] INPUT  -
    [1] {"id":1,"method":"Page.setDownloadBehavior","params": 
    {"behavior":"allow","downloadPath":"C:\\Users\\Jessie\\repos\\rpa"}}
    [tagui] OUTPUT -
    [1] {"id":1,"result":{}}

No Command Prompt opens when shell=False, which is the default behavior for subprocess.Popen():
https://docs.python.org/3.8/library/subprocess.html#subprocess.Popen

I'm running Python 3.8.3 and using the PyCharm IDE. I'm also executing r.init() and r.url() in a wxPython GUI application loop, launched within a multiprocessing Process.  Docs:
https://docs.python.org/3.8/library/multiprocessing.html#multiprocessing.Process

**Comment by kensoh** [comment] 2022-04-17 13:24
Hi @jesuisme thanks for sharing this! I get your intention now. Can I check with you, other than the command prompt not showing up, is there any other differences when you use the rpa package with shell = False compared to shell = True?

I should be keeping this issue open for some time to see if any other users have this use case. I'll prefer not to add options which are not used by many users, because it will quickly make the API more complex and harder to use. Also, for the time being, I don't have a Windows laptop to validate and do extensive testing.

**Comment by jesuisme** [comment] 2022-04-18 17:16
@kensoh I haven't noticed any other differences. But, I'm not doing much beyond what's in the examples.

I totally understand regarding the API. Thanks again for the work on the module!

**Comment by kensoh** [comment] 2022-04-29 09:44
Until I get access to a Windows laptop, @jesuisme, could you try to run the following on your modified package without the command prompt windows opening, and let me know the output? And also what is in rpa_python.log file?

```py
import rpa as r
r.debug(True)
r.init()
r.url('https://ca.yahoo.com')
r.type('ybar-sbq', 'github')
print(r.read('ybar-sbq'))
r.click('ybar-search')
r.wait(6.6)
r.snap('page', 'results.png')
r.snap('logo', 'logo.png')
r.close()
```

Previously when I tried to hide the command prompt on the TagUI engine on Windows, all the data in the transactional windows get routed to the main TagUI command prompt and messes up the output. Not sure if doing it from Python process will lead to similar side effects.

**Comment by kensoh** [comment] 2022-05-01 15:48
Adding some dev notes -

Running on Mac / Linux with `shell=True` requires `tagui_cmd.split()` in the subprocess.Popen() function call, otherwise the invocation of TagUI will fail. Current implementation has double quotes enclosure to support folder paths with spaces.

Trying without double quotes and sending in tagui_cmd as a command file path and parameters list, seems to be unable to launch the process successfully for folder paths with spaces. At least for Mac, not sure of Linux.

**Comment by kensoh** [comment] 2022-05-01 22:29
In the meantime, I was able to briefly access a Windows laptop. To run with shell=False on Windows, for rpa v1.47, I have to make the following changes. 1. remove the double quotes in the tagui_cmd, 2. add .cmd, 3. add tagui_cmd.split() and 4. set shell=False. However, after adding all these, there is still the Chrome Engine command prompt window on execution.

**tagui.py**
```py
    # entry shell command to invoke tagui process
    tagui_cmd = '' + tagui_executable + '.cmd' + ' rpa_python ' + browser_option

    # run tagui end processes script to flush dead processes
    # for eg execution ended with ctrl+c or forget to close()
    os.system('"' + end_processes_executable + '"')

    try:
        # launch tagui using subprocess
        _process = subprocess.Popen(
            tagui_cmd.split(), shell=False,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
```

Thus I'm leaning to keeping `shell=True` unchanged, given the complications with Mac / Linux to run properly, and even on Windows (tested on Windows 10), running with `shell=False` still result in having the Chrome Engine command prompt window. On your environment it works, but on the Windows I tested on it doesn't. Probably means that the setting has sensitivity to environments, which would make it hard to generalise to work correctly on various environments.

**Comment by jesuisme** [comment] 2022-05-01 22:53
@kensoh I think you're right that environments/paths may be playing a role; I didn't have to make any of those changes. It may also make a difference that I'm running on Windows 11 and that I'm starting the rpa instance in a separate process, not a Pipe.

When I run the automation code from above, everything seems to work as expected and the command prompt does not appear.  The logo.png file contains the Yahoo! logo and results.png contains the search results for GitHub. Contents of the rpa.log:

```
START - automation started - Sun May 01 2022 17:23:50 GMT-0500 (Central Daylight Time)

LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://ca.yahoo.com
[RPA][1] - listening for inputs
[RPA][2] - exist_result = exist('ybar-sbq').toString()
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
[RPA][3] - listening for inputs
[RPA][4] - type ybar-sbq as github
[RPA][4] - listening for inputs
[RPA][5] - exist_result = exist('ybar-sbq').toString()
[RPA][5] - listening for inputs
[RPA][6] - dump exist_result to rpa_python.txt
[RPA][6] - listening for inputs
[RPA][7] - read ybar-sbq to read_result
[RPA][7] - listening for inputs
[RPA][8] - dump read_result to rpa_python.txt
[RPA][8] - listening for inputs
[RPA][9] - exist_result = exist('ybar-search').toString()
[RPA][9] - listening for inputs
[RPA][10] - dump exist_result to rpa_python.txt
[RPA][10] - listening for inputs
[RPA][11] - click ybar-search
[RPA][11] - listening for inputs
[RPA][12] - snap page to results.png
[RPA][12] - listening for inputs
[RPA][13] - exist_result = exist('logo').toString()
[RPA][13] - listening for inputs
[RPA][14] - dump exist_result to rpa_python.txt
[RPA][14] - listening for inputs
[RPA][15] - snap logo to logo.png
[RPA][15] - listening for inputs
[RPA][FINISHED]

https://ca.search.yahoo.com/search?p=github&fr=yfp-t&fp=1&toggle=1&cop=mss&ei=UTF-8 - github - Yahoo Canada Search Results
FINISH - automation finished - 18.6s
```

Thanks for investigating -- probably time to close ;-)

**Comment by kensoh** [comment] 2022-05-02 15:48
Hi @jesuisme, Larry, thanks for the suggestion nevertheless! I'll close the issue, but will watch out for future requests by other users. It does sound that it works on Windows 11 but not Windows 10. Shall archive this change for now.

In the meantime, I've made 2 commits in your name and rolled back. To register your contribution and idea. Your name should show up shortly in the contributors history of the package -

https://github.com/tebelorg/RPA-Python/graphs/contributors

**Closed** 2022-05-02 15:48 UTC
Labels: feature
