### ISSUE TITLE
Error with the sample code - from log looks like Python env setup issue

### ISSUE THREAD

**Issue by KayRohde** [tebelorg/RPA-Python#129] opened 2020-04-22 14:45 UTC
Hey there,

I tried to run the sample code, but I am getting an AttributeError : `partially initialized module 'rpa' has no attribute 'init' (most likely due to a circular import)`.

I installed rpa and then just made the same as it is in the sample code but it does not work. I am working on macOS Majove v. 10.14.6.

I tried it with visual studio code and with pycharm. 

Best regards
Kay

**Comment by kensoh** [comment] 2020-04-22 19:18
Hi Kay, can you tell me the exact steps that you do from your computer to run the sample code?

The tool has been installed by thousands of users and I haven't come across this error before. I assume you have installed the package by opening Terminal app and typing `pip install rpa`.

Can you also try the following to see if there are more clues?
1. open Terminal app and type `pip list`
2. see if there is `rpa 1.26.1`and `tagui 1.26.1`?
3. download the [sample.py script](https://github.com/tebelorg/RPA-Python/raw/master/sample.py) that comes with the repo
4. run python sample.py to see if the same error appears

**Comment by KayRohde** [comment] 2020-04-22 20:37
Hey Kensoh,

thanks for your response. The exact steps I did was like you said `pip install rpa`, after that take the sample code and run it with `python sample.py` like you said and I tested it again and I am getting this error ```
Traceback (most recent call last):
  File "sample.py", line 7, in <module>
    import rpa as r
ImportError: No module named rpa
```.

When typing pip list it shows me `rpa 1.26.1` and `tagui 1.26.1`. 

The error I described before came when I used PyCharm. 

I am not sure if I am doing something wrong, but I mean its straight forward just installing and running I dont know.

**Comment by KayRohde** [comment] 2020-04-22 20:48
Actually I tried it again with `python3 sample.py`. Now it worked but I am getting this: ```[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - /Users/kayrohde
[RPA][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_macOS.zip...
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()```

Is this maybe because I am doing it on my macbook from work?

**Comment by kensoh** [comment] 2020-04-23 16:21
From above info, it looks like the setup on your computer, the `python` command calls Python v2, but the `pip` command maybe is install for Python v3. For Python, v2 and v3 have separate environments. Installing packages on one will not make it work on the other. That is most likely the root cause of your initial error message which you solve by running `python3` instead.

**Comment by kensoh** [comment] 2020-04-23 16:28
For the second error message above, this is because Python 3 no longer can depend on macOS OpenSSL (Apple removed it). Because of that, Python 3 user normally will need to install the SSL certificates manually. See more [details here]( https://medium.com/@yen.hoang.1904/resolve-issue-ssl-certificate-verify-failed-when-trying-to-open-an-url-with-python-on-macos-46d868b44e10) of this issue and the solution.

```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
```


&ensp;
**Additional Note**

For RPA for Python, when you run it the first time, it will try to automatically run the commands in above Medium post for you. But from your run log above, it looks like for some reason it cannot be automatically installed. It could be due to restricted user permissions on your work laptop or other reasons. You can try installing manually by following the steps in above Medium post and try again.

**Comment by kensoh** [comment] 2020-04-28 17:16
Closing issue for now until further inputs, as it looks to be related to Python environment issue.

**Closed by kensoh** 2020-04-28 17:16 UTC
Labels: query
